In [1]:
import os
import pandas as pd

In [2]:
os.chdir('../kashish files/output')
os.listdir()

['Company_Exhaustive_List.csv',
 'Company_Tweepy_Verified.csv',
 'Company_Twint_Verified.csv',
 'Gsearch1.csv',
 'Gsearch2.csv',
 'Gsearch3.csv',
 'Gsearch4.csv',
 'Kashish_GoogleSearcher_CompanyHandles_verified.csv']

In [47]:
df= pd.read_csv('old/Company_Twint_Verified.csv')
df.shape

(387, 25)

In [48]:
df.drop_duplicates(inplace=True)
df.shape

(387, 25)

In [49]:
df.drop(['CEO Name', 'EXECID', 'YEAR','profile_image_url', 'background_image', 'url'], axis=1)

,Company,GVKEY,trimmed_company_name,Company_Handles,small_username,id,name,username,bio,location,join_date,join_time,tweets,following,followers,likes,media,private,verified
0,AMERICAN AIRLINES GROUP INC,1045,american airlines group,americanair,americanair,2.253606e+07,americanair,AmericanAir,Official Twitter for the world’s largest airli...,NaN,02-03-2009,21:23:05 UTC,2283208.0,106034.0,1607939.0,4989.0,2233.0,False,True
1,ABBOTT LABORATORIES,1078,abbott laboratories,abbottglobal,abbottglobal,1.934702e+09,Abbott,AbbottGlobal,The @AbbottGlobal Twitter page was discontinue...,"Abbott Park, Illinois",04-10-2013,16:08:08 UTC,5946.0,3039.0,35200.0,6872.0,2085.0,False,True
2,ADVANCED MICRO DEVICES,1161,advanced micro devices,amd,amd,1.486188e+07,AMD,AMD,Official corporate news about the AMD technolo...,"Austin, TX",21-05-2008,22:14:12 UTC,8930.0,256.0,965264.0,8965.0,1879.0,False,True
3,AETNA INC,1177,aetna,aetna,aetna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,AIR PRODUCTS & CHEMICALS INC,1209,air products & chemicals,AirProducts,airproducts,1.096350e+08,Air Products,airproducts,"Industry-leading company of 19,000+ dedicated ...",Worldwide,29-01-2010,18:52:02 UTC,3806.0,550.0,11374.0,278.0,925.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,AMERICAN CAPITAL LTD,65345,american capital ltd,abcapital,abcapital,8.470000e+17,Aditya Birla Capital,abcapital,Protecting | Investing | Financing,"Mumbai, India",29-03-2017,16:22:11 UTC,3479.0,65.0,22118.0,359.0,198.0,False,True
383,ILLUMINA INC,138205,illumina inc,illumina,illumina,4.614576e+07,Illumina,illumina,Illumina is dedicated to advancing human healt...,"San Diego, CA",10-06-2009,15:59:29 UTC,14116.0,9653.0,84362.0,8229.0,1080.0,False,True
384,ALPHA NATURAL RESOURCES INC,162448,alpha natural resources,ONresources,onresources,2.024862e+07,Ontario MNRF,ONresources,Official account of Ontario’s Ministry of Natu...,"Ontario, Canada",06-02-2009,16:22:26 UTC,11005.0,1756.0,32352.0,2318.0,4107.0,False,True
385,EMBARQ CORP,174130,embarq corp,centurylink,centurylink,4.418224e+07,CenturyLink,CenturyLink,Transforming lives and businesses through inno...,NaN,02-06-2009,19:07:02 UTC,10240.0,449.0,39050.0,3473.0,3048.0,False,True
386,PHILIP MORRIS INTERNATIONAL,179621,philip morris international,InsidePMI,insidepmi,9.143113e+08,Philip Morris International,InsidePMI,We’re designing a #smokefree future. Find out ...,Worldwide,30-10-2012,10:14:32 UTC,7481.0,126.0,28656.0,642.0,3728.0,False,True

In [52]:
df= df[['GVKEY', 'Company', 'Company_Handles', 'bio', 'verified']]
df

,GVKEY,Company,Company_Handles,bio,verified
0,1045,AMERICAN AIRLINES GROUP INC,americanair,Official Twitter for the world’s largest airli...,True
1,1078,ABBOTT LABORATORIES,abbottglobal,The @AbbottGlobal Twitter page was discontinue...,True
2,1161,ADVANCED MICRO DEVICES,amd,Official corporate news about the AMD technolo...,True
3,1177,AETNA INC,aetna,NaN,True
4,1209,AIR PRODUCTS & CHEMICALS INC,AirProducts,"Industry-leading company of 19,000+ dedicated ...",True
...,...,...,...,...,...
382,65345,AMERICAN CAPITAL LTD,abcapital,Protecting | Investing | Financing,True
383,138205,ILLUMINA INC,illumina,Illumina is dedicated to advancing human healt...,True
384,162448,ALPHA NATURAL RESOURCES INC,ONresources,Official account of Ontario’s Ministry of Natu...,True
385,174130,EMBARQ CORP,centurylink,Transforming lives and businesses through inno...,True
386,179621,PHILIP MORRIS INTERNATIONAL,InsidePMI,We’re designing a #smokefree future. Find out ...,True

In [53]:
df.dropna(subset=['Company_Handles'], inplace=True)

In [8]:
set(df.drop_duplicates(subset=['Company'])['Company'].tolist()).difference(set(df.drop_duplicates(subset=['trimmed_company_name'])['Company'].tolist()))

{'BROADCOM INC', 'CHUBB LTD'}

In [9]:
df[df.trimmed_company_name.str.contains('chubb')]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
39,3024,CHUBB CORP,chubb,chubb,Chubb,Chubb is the world’s largest publicly traded p...,12-05-2009,4933.0,806.0,27576.0,502.0,2350.0,False,True
258,28034,CHUBB LTD,chubb,chubb,Chubb,Chubb is the world’s largest publicly traded p...,12-05-2009,4933.0,806.0,27576.0,502.0,2350.0,False,True

In [10]:
df['Company'].value_counts()

BURLINGTON NORTHERN SANTA FE    2
NIKE INC  -CL B                 2
TRAVELERS COS INC               1
KB HOME                         1
GOLDMAN SACHS GROUP INC         1
                               ..
EASTMAN CHEMICAL CO             1
BEAM INC                        1
PAYPAL HOLDINGS INC             1
EL PASO CORP                    1
AVON PRODUCTS                   1
Name: Company, Length: 385, dtype: int64

In [11]:
df[df.Company.str.contains('NIKE INC  -CL B')]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
133,7906,NIKE INC -CL B,nike,Nike,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
371,7906,NIKE INC -CL B,nike,nike,Nike,#BlackLivesMatter,18-11-2011,36994.0,117.0,8340480.0,6988.0,3106.0,False,True

In [12]:
df[df.Company.str.contains('BURLINGTON NORTHERN SANTA FE')]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
30,2490,BURLINGTON NORTHERN SANTA FE,burlington northern santa,metraBNF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
366,2490,BURLINGTON NORTHERN SANTA FE,burlington northern santa,metraBNSF,Metra BNSF,Metra provides service to and from downtown Ch...,20-02-2009,11003.0,0.0,11801.0,9.0,93.0,False,True

In [13]:
df.name.value_counts()

Republic Services          2
Pepsi                      2
Chubb                      2
The Kraft Heinz Company    2
Broadcom Inc.              2
                          ..
Office Depot               1
HPE                        1
American Express           1
Avery Dennison             1
Express Scripts            1
Name: name, Length: 368, dtype: int64

In [16]:
df[df.name.isna()]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
3,1177,AETNA INC,aetna,aetna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
15,1690,APPLE INC,apple,Apple,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
30,2490,BURLINGTON NORTHERN SANTA FE,burlington northern santa,metraBNF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
58,3980,DISNEY (WALT) CO,disney (walt),disney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
133,7906,NIKE INC -CL B,nike,Nike,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
222,15708,ALLERGAN INC,allergan inc,allerganeye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
239,24616,PAYPAL HOLDINGS INC,paypal holdings,paypal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
246,25283,KOHL'S CORP,kohl's corp,kohls,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
259,28118,FOSSIL GROUP INC,fossil group,fossil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
278,60900,DISH NETWORK CORP,dish network,dish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
290,63643,ABERCROMBIE & FITCH -CL A,abercrombie & fitch,Abercrombie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [17]:
df.dropna(subset=['name'], inplace=True)

In [18]:
df[df.name.str.contains('Pepsi')]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
144,8479,PEPSICO INC,pepsico,Pepsi,Pepsi,If you’re looking for hot takes and cold Pepsi...,15-12-2008,54756.0,38899.0,2999906.0,6069.0,3614.0,False,True
311,119417,PEPSI BOTTLING GROUP INC,pepsi bottling group,Pepsi,Pepsi,If you’re looking for hot takes and cold Pepsi...,15-12-2008,54756.0,38899.0,2999906.0,6069.0,3614.0,False,True

In [20]:
df.Company_Handles.value_counts()[:20]

ThermoFisher       2
KraftHeinzCo       2
Broadcom           2
centurylink        2
Pepsi              2
chubb              2
Lowes              2
RepublicService    2
discovery          1
3M                 1
ElPasoTXGov        1
carmax             1
PVHCorp            1
wastemanagement    1
ChampionsLeague    1
citi               1
MSCI_Inc           1
ktla               1
PPLElectric        1
goldmansachs       1
Name: Company_Handles, dtype: int64

In [21]:
df.verified.value_counts()

True    376
Name: verified, dtype: int64

In [22]:
df.to_csv('Kashish_GoogleSearcher_CompanyHandles_verified.csv', index=False)

In [54]:
df.reset_index(inplace=True)
df.drop('index', axis=1, inplace=True)

In [25]:
df.iloc[189:283]

,GVKEY,Company,trimmed_company_name,Company_Handles,name,bio,join_date,tweets,following,followers,likes,media,private,verified
189,12151,COTY INC,coty,cotyinc,Coty Inc.,We celebrate and liberate the diversity of you...,06-01-2012,831.0,536.0,6043.0,174.0,294.0,False,True
190,12206,DIRECTV,directv,directv,DIRECTV,ATT/DIRECTV is ranked #1 in Nationally in Cust...,29-05-2008,84804.0,1746.0,255191.0,8061.0,7696.0,False,True
191,12389,HARLEY-DAVIDSON INC,harley-davidson,harleydavidson,Harley-Davidson,The official Twitter feed for the Harley-David...,04-11-2008,16818.0,1440.0,450500.0,6756.0,6773.0,False,True
192,12441,GARTNER INC,gartner,gartner_inc,Gartner,"We’re here to help: View our insights, advice ...",25-06-2008,27742.0,49926.0,407043.0,5717.0,7376.0,False,True
193,12540,ADOBE INC,adobe,Adobe,Adobe,Creativity doesn’t just open doors. It opens w...,07-08-2009,41306.0,213.0,685816.0,13755.0,10645.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,63080,ANSYS INC,ansys,ansys,Ansys,Official Ansys Twitter. #engineering #simulati...,20-04-2009,21266.0,3018.0,23916.0,7491.0,8192.0,False,True
279,63501,E TRADE FINANCIAL CORP,e trade financial,etrade,E*TRADE,Welcome to E*TRADE. Follow us for financial in...,17-04-2009,18842.0,545.0,74850.0,1610.0,1334.0,False,True
280,63669,UNIVISION COMMUNICATIONS INC,univisionmmunications,univision,Univision,"El lugar número 1 para tus noticias, entreteni...",18-05-2009,167224.0,3237.0,2743028.0,2402.0,80986.0,False,True
281,63892,NATIONAL OILWELL VARCO INC,national oilwell varco,NOVGlobal,NOV,The official Twitter page of National Oilwell ...,25-06-2014,1604.0,315.0,5714.0,629.0,909.0,False,True
282,64156,MONSTER WORLDWIDE INC,monster worldwide,Monster,Monster,Find the right fit. \n\nhttps://t.co/bk1wBj1rXY,14-02-2007,614508.0,5851.0,218318.0,23923.0,6826.0,False,True

In [26]:
df.iloc[:95].to_csv('Gsearch1.csv')
df.iloc[96:189].to_csv('Gsearch2.csv')
df.iloc[189:283].to_csv('Gsearch3.csv')
df.iloc[283:].to_csv('Gsearch4.csv')

In [27]:
dff=pd.read_excel(r'../../input/SnP_500_CEO_Names.xlsx')
dff.dropna(inplace=True)
dff.drop(['CEO Name', 'YEAR'], axis=1, inplace=True)
dff.drop_duplicates(subset=['Company'], inplace=True)
dff.shape

(782, 3)

In [28]:
a=df.Company.tolist()

In [29]:
df1=dff[~dff.Company.isin(a)]

In [30]:
df1

                           Company   GVKEY  EXECID
0       ADC TELECOMMUNICATIONS INC    1013   10203
17      PINNACLE WEST CAPITAL CORP    1075   10739
56                       AETNA INC    1177   14660
93            ALLEGHENY ENERGY INC    1279    5899
110                    ALLTEL CORP    1318   12422
...                            ...     ...     ...
8598            CAPRI HOLDINGS LTD  198058   45334
8628     WELLCARE HEALTH PLANS INC  260778   31719
8640  LYONDELLBASELL INDUSTRIES NV  294524   31023
8651                  ALLEGION PLC  316056   34850
8658            NVENT ELECTRIC PLC  326688   49088

[406 rows x 3 columns]

In [31]:
df1.to_csv('GSearch_failed_Handles.csv', index=False)

In [32]:
import tweepy
import pandas as pd
import numpy as np

# assign the values accordingly 
consumer_key = "OMJv2A5J1XvXdBSLykjbzQvjN" 
consumer_secret = "IF1tUCs5uFhKNN4PILugYgTdfaFDEakS4gbzWHKEL92dIoSRHA" 
access_token = "3097042092-HXzJwRZ4BRSiTa67RfHnlE7CeF01gutElIP6UoT" 
access_token_secret = "kZYcycMakp0z3jcGC07UpLynOWvvtoBiAmwVjJKziSYB8"

# authorization of consumer key and consumer secret 
auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
# set access to user's access key and access secret  
auth.set_access_token(access_token, access_token_secret) 
  
# calling the api  
api = tweepy.API(auth, wait_on_rate_limit=True)

In [33]:
from collections import Counter
cnt = Counter()
for text in df1["Company"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(30)

[('INC', 194),
 ('CORP', 108),
 ('CO', 35),
 ('PLC', 21),
 ('ENERGY', 19),
 ('HOLDINGS', 17),
 ('&', 17),
 ('GROUP', 16),
 ('TECHNOLOGIES', 10),
 ('FINANCIAL', 9),
 ('INTL', 9),
 ('LTD', 8),
 ('INDUSTRIES', 7),
 ('RESOURCES', 7),
 ('INTERNATIONAL', 6),
 ('REALTY', 6),
 ('HEALTH', 6),
 ('BRANDS', 5),
 ('SYSTEMS', 5),
 ('CITY', 4),
 ('COS', 4),
 ('NATIONAL', 4),
 ('TECHNOLOGY', 4),
 ('UNITED', 4),
 ('PROPERTY', 4),
 ('SOLUTIONS', 3),
 ('AMERICAN', 3),
 ('MATERIALS', 3),
 ('GLOBAL', 3),
 ('SOUTHERN', 3)]

In [34]:
df=df1
df1.shape

(406, 3)

In [35]:
df['Company']= df['Company'].str.replace(r"\(.*\)","")
df['Company']= df['Company'].str.replace(' -CL A', '')
df['Company']= df['Company'].str.replace(' -CL B', '')
df['Company']= df['Company'].str.replace('/DE', '')
df['Company']= df['Company'].str.replace('/ME', '')
#df['Company']= df['Company'].str.replace(r'\([^()]*\)', '')
df['Company']= df['Company'].str.replace('ARCHER-DANIELS-MIDLAND CO', 'ARCHER-DANIELS-MIDLAND')
df['Company']= df['Company'].str.strip()

<ipython-input-35-918051c6f60a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace(r"\(.*\)","")
<ipython-input-35-918051c6f60a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace(' -CL A', '')
<ipython-input-35-918051c6f60a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace(' -CL B', '')
<ipython-input-35-918051c6f60a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace('/DE', '')
<ipython-input-35-918051c6f60a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace('/ME', '')
<ipython-input-35-918051c6f60a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.replace('ARCHER-DANIELS-MIDLAND CO', 'ARCHER-DANIELS-MIDLAND')
<ipython-input-35-918051c6f60a>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df['Company'].str.strip()

In [36]:
cp=[]
for i in df.Company:
    a=i.split()
    if len(a)==6:
        i=i.replace(' CORP', '')
        cp.append(i)
        #print(i) 
    elif len(a)>=3:
        #i=i.join(content.split(' ')[:-1])
        i= i.replace(' INC', '')
        i= i.replace(' INTL', '')
        i= i.replace(' CORP', '')
        i= i.replace(' CO', '')
        i= i.replace(' COS', '')
        i= i.replace(' PLC', '')
        i= i.replace(' GRP', '')
        i= i.replace(' GROUP', '')
        
        i= i.replace(' SVCS', '')
        i= i.replace(' PLC', '')
        i= i.replace('\/.*$', '')
        cp.append(i)
    else:
        cp.append(i)
               
    
len(cp)

406

In [37]:
df['Company']=cp

<ipython-input-37-9082fa34ac59>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']=cp

In [38]:
df['Company'] = df['Company'].str.replace('-', ' ')
df['Company']= df.Company.str.strip()

<ipython-input-38-2da13a37bbbd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company'] = df['Company'].str.replace('-', ' ')
<ipython-input-38-2da13a37bbbd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company']= df.Company.str.strip()

In [41]:
tdf=pd.DataFrame()
companies=[]
gvk=[]
handles=[]
descriptions=[]
verified=[]

badnames=[]
badgv=[]

for i in range(len(df)):
    users = api.search_users(df.iloc[i]['Company'])                     
    lst=[]
    for user in users:
        lst.append(user.screen_name)
    if len(lst)==0:
        badnames.append(df.iloc[i]['Company'])
        badgv.append(df.iloc[i]['GVKEY'])
        print('--------------------------------- ',df.iloc[i]['Company'],'---------------------------------' )
    for j in lst:
        obj=api.get_user(j)
        result=obj.verified
        if result==True:
            companies.append(df.iloc[i]['Company'])
            gvk.append(df.iloc[i]['GVKEY'])
            handles.append(j)
            descriptions.append(obj.description)
            verified.append(result)
            print(df.iloc[i]['Company'], j)

---------------------------------  ADC TELECOMMUNICATIONS ---------------------------------
---------------------------------  PINNACLE WEST CAPITAL ---------------------------------
AETNA INC Aetna
---------------------------------  ALLTEL CORP ---------------------------------
AMERICAN ELECTRIC POWER AEPnews
---------------------------------  NABORS INDUSTRIES LTD ---------------------------------
APPLE INC Apple
APPLE INC pschiller
APPLE INC AngelaAhrendts
APPLE INC BoysStateMovie
APPLE INC trippmickle
APPLE INC DaveAtBEATS
---------------------------------  ASHLAND GLOBAL HOLDINGS ---------------------------------
SOUTHERN GAS SSGC_Official
AUTOMATIC DATA PROCESSING ADP
BAKER HUGHES Avitas_Systems
CONSTELLATION ENERGY ConstellationEG
BANK OF NEW YORK MELLON BNYMellon
---------------------------------  UNISYS CORP ---------------------------------
---------------------------------  CSX CORP ---------------------------------
PROGRESS ENERGY EnergyCIO
PROGRESS ENERGY Shell_US
PROGRESS ENERGY mankofit
PROGRESS ENERGY Exelon
---------------------------------  CIRCUIT CITY STORES ---------------------------------
CA INC MarvelStudiosCA
CA INC eBayCanada
CA INC CAinc
CA INC CA_IM
COOPERS PwC
COOPERS PwCUS
COOPERS PwC_UK
COOPERS coopers_craft
COOPERS PwC_Nigeria
COOPERS PwCTax
COUNTRYWIDE FINANCIAL BankofAmerica
COUNTRYWIDE FINANCIAL BofA_News
COUNTRYWIDE FINANCIAL BofA_Tips
DISNEY  CO WaltDisneyCo
DISNEY  CO WDWToday
DISNEY  CO DisneyPlusUK
DISNEY  CO DisneyXDUK
DISNEY  CO PixarSoul
DISNEY  CO DisneyCareers
DISNEY  CO DisneyGiftCard
DISNEY  CO Disney_Insiders
DISNEY  CO DisneyStudiosIE
DISNEY  CO DisneyPlusHelp
DISNEY  CO abigaildisney
DISNEY  CO WDWGuestService
DISNEY  CO hotstar_helps
DOLLAR GENERAL DollarGeneral
DU PONT  DE NEMOURS DuPont_News
EATON eatoncorp
EATON AshtonJEaton
EATON AbbieEaton44
EATON georgeeaton
EATON MerEaton
EATON btheiseneaton
EATON BrandoEaton
EATON joshua_eaton
EATON LongEatonNorth
EATON courtneyeaton
EATON njerieaton
EATON PaulDEaton52
EATON CollinEatonHC
---------------------------------  EXPEDITORS WASH ---------------------------------
---------------------------------  FEDERAL NATIONAL MORTGA ASSN ---------------------------------
---------------------------------  FEDERAL REALTY INVESTMENT TR ---------------------------------
---------------------------------  FIRST HORIZON NATIONAL ---------------------------------
FOREST LABORATORIES meury_bill
GENUINE PARTS GMParts_ACDelco
GENUINE PARTS NAPAKnowHow
GENUINE PARTS baxiboilers
---------------------------------  WELLTOWER INC ---------------------------------
---------------------------------  HOLLYFRONTIER CORP ---------------------------------
---------------------------------  INTL BUSINESS MACHINES ---------------------------------
---------------------------------  INTL FLAVORS & FRAGRANCES ---------------------------------
JACOBS ENGINEERING UCSDJacobs
JACOBS ENGINEERING FredericJacobs
SEARS HOLDINGS Sears
KANSAS CITY SOUTHERN ATFKansasCity
KANSAS CITY SOUTHERN ETeaparty25
LEGG MASON CitiOpen
JEFFERIES FINANCIAL HandlerRich
L BRANDS LNforBrands
L BRANDS l3pje
L BRANDS LVMH
L BRANDS MDLZ
L BRANDS BATplc
L BRANDS joeybrezinski
RANGE RESOURCES SignifyUni
---------------------------------  MARSH & MCLENNANS ---------------------------------
---------------------------------  MARSHALL & ILSLEY ---------------------------------
---------------------------------  MASCO CORP ---------------------------------
MCCORMICK & SierraNMcCormic
MCCORMICK & McCormickCorp
MCCORMICK & mccormickspices
MCCORMICK & TyMcCormick
MCCORMICK & McCormickJohn
MCCORMICK & KathrynrMcc
MCCORMICK & neil_mccormick
MCCORMICK & cmccormick08
MCCORMICK & sadogre
MCCORMICK & emily_mcck
MCCORMICK & HyattMcCormick
MCCORMICK & McCormick4Chefs
MCCORMICK & RichforGA
---------------------------------  MEDCO HEALTH SOLUTIONS ---------------------------------
MERRILL LYNCH & MerrillLynch
MERRILL LYNCH & SallieKrawcheck
MERRILL LYNCH & MarshallM13
---------------------------------  MOLEX INC ---------------------------------
MYLAN NV MylanNews
NATIONAL CITY CityOfNatlCity
NATIONAL CITY CityNational
NATIONAL CITY OKCNM
NATIONAL CITY NWSKansasCity
NATIONAL CITY NACCHOalerts
NATIONAL CITY NALC_National
NATIONAL CITY OfficialClarets
NATIONAL CITY BathCity_FC
---------------------------------  NICOR INC ---------------------------------
XCEL ENERGY XcelEnergyCtr
---------------------------------  ONEOK INC ---------------------------------
PPG INDUSTRIES PPG
---------------------------------  PACCAR INC ---------------------------------
---------------------------------  PARKER HANNIFIN CORP ---------------------------------
---------------------------------  PENTAIR PLC ---------------------------------
APPLIED BIOSYSTEMS thermofisher
RAYMOND JAMES FINANCIAL RaymondJames
RAYMOND JAMES FINANCIAL JustinWTSP
AUTONATION INC CEOMikeJackson
---------------------------------  ROHM AND HAAS ---------------------------------
---------------------------------  ROWANMPANIES ---------------------------------
---------------------------------  SAFECO CORP ---------------------------------
---------------------------------  SCANA CORP ---------------------------------
SCHERING PLOUGH Merck
SMITH OfficialWillow
SMITH RogerCraigSmith
SMITH bastilledan
SMITH ThatKevinSmith
SMITH EmmittSmith22
SMITH jaden
SMITH TheJetOnTNT
SMITH SenTinaSmith
SMITH TheRealJRSmith
SMITH TeamJuJu
SMITH BradSmi
SMITH BrianJacobSmith
SMITH ememess
SMITH BustaRhymes
SMITH aetiology
SMITH BradleySmith38
SMITH michaelwsmith
SMITH TorreySmithWR
SMITH SenHydeSmith
---------------------------------  TEMPLE INLAND INC ---------------------------------
---------------------------------  TERADYNE INC ---------------------------------
---------------------------------  ENERGY FUTURE HOLDINGS ---------------------------------
GLOBE LIFE GlobeLifeField
GLOBE LIFE TIME
GLOBE LIFE TEXPAMAN
TYCO INTERNATIONAL johnsoncontrols
UNITED PARCEL SERVICE UPS
UNIVERSAL HEALTH CHGlobalHealth
UNIVERSAL HEALTH WHOMalaysia
---------------------------------  VORNADO REALTY TRUST ---------------------------------
WENDY'S INTERNATIONAL Wendys
WENDY'S INTERNATIONAL CaitlinSinett
---------------------------------  MEADWESTVACO CORP ---------------------------------
---------------------------------  WEYERHAEUSER CO ---------------------------------
WEC ENERGY aBayraktar1
---------------------------------  INTEGRYS HOLDING ---------------------------------
---------------------------------  ZIONS BANCORPORATION NA ---------------------------------
---------------------------------  BEAR STEARNSMPANIES ---------------------------------
TRUIST FINANCIAL TruistNews
NOBLE NobleGG
NOBLE realrossnoble
NOBLE BNBuzz
NOBLE safiyanoble
NOBLE nookBN
NOBLE Noble16Mark
NOBLE YOUNG_NOBLE1
NOBLE ukinromania
NOBLE BeNobleSchools
NOBLE Nobsdaslushhkid
NOBLE kezia_noble
---------------------------------  EMC CORP/MA ---------------------------------
SUN MICROSYSTEMS Oracle
SUN MICROSYSTEMS alpresnell
SUN MICROSYSTEMS OracleANZ
SUN MICROSYSTEMS Oracle_CH
SUN MICROSYSTEMS larryellison
---------------------------------  GENZYME CORP ---------------------------------
---------------------------------  AIRGAS INC ---------------------------------
JOY GLOBAL VDay
SYNOVUS FINANCIAL synovus
---------------------------------  HEALTHPEAK PROPERTIES ---------------------------------
---------------------------------  PROGRESSIVE CORP OHIO ---------------------------------
---------------------------------  BARR PHARMACEUTICALS ---------------------------------
---------------------------------  CARNIVALORATION & ---------------------------------
---------------------------------  ZOETIS INC ---------------------------------
---------------------------------  MAXIM INTEGRATED PRODUCTS ---------------------------------
---------------------------------  ALTERA CORP ---------------------------------
CINCINNATI FINANCIAL CincyTennis
CINCINNATI FINANCIAL UnitedWayGC
---------------------------------  LABORATORY CP OF AMER HLDGS ---------------------------------
ALLERGAN INC meury_bill
WASHINGTON MUTUAL indiviglio
---------------------------------  PEOPLE'S UNITED FINL ---------------------------------
---------------------------------  COMMERCE BANCORP/NJ ---------------------------------

SVB FINANCIAL SVB_Financial
SVB FINANCIAL SVB_UK
SVB FINANCIAL KateDMitchell
SVB FINANCIAL dkimerling
---------------------------------  SANTANDER HOLDINGS USA ---------------------------------
---------------------------------  IQVIA HOLDINGS ---------------------------------
---------------------------------  MALLINCKRODT PLC ---------------------------------
TWITTER INC Twitter
TWITTER INC TwitterData
TWITTER INC WWE
TWITTER INC SEGA
TWITTER INC INCIndia
TWITTER INC amazon
TWITTER INC acnnews
TWITTER INC GoPro
TWITTER INC WWEUniverse
TWITTER INC MarvelMusicInc
TWITTER INC MarvelUK
TWITTER INC amazonIN
TWITTER INC CanonUSA
TWITTER INC ASUS
TWITTER INC Stussy
TWITTER INC InterFM897
TWITTER INC gmanetwork
TWITTER INC HondaCanada
TWITTER INC ANSYS
---------------------------------  DENBURY RESOURCES ---------------------------------
---------------------------------  ALLIED WASTE INDUSTRIES ---------------------------------
---------------------------------  BAXALTA INC ---------------------------------
---------------------------------  PMC SIERRA INC ---------------------------------
---------------------------------  CEPHALON INC ---------------------------------
UNITED STATES STEEL dennisogbe
JONES OwenJones84
JONES KySportsRadio
JONES actordougjones
JONES ManMadeMoon
JONES MotherJones
JONES Lesdoggg
JONES DowJones
JONES JonnyBones
JONES luciejones1
JONES Nas
JONES RealCJ10
JONES RealSirTomJones
JONES themiltonjones
JONES curtisjr_10
JONES VinnieJones65
JONES Byron31Jump
JONES JessicaJones
JONES theferocity
---------------------------------  AMBAC FINANCIAL ---------------------------------
MONSTER BEVERAGE MonsterEnergy
XL LTD qikipedia
---------------------------------  MGIC INVESTMENT/WI ---------------------------------
PAYPAL HOLDINGS PayPal
PAYPAL HOLDINGS PayPalUK
PERRIGO billyperrigo
---------------------------------  ROPER TECHNOLOGIES ---------------------------------
SYNOPSYS INC SW_Integrity
---------------------------------  KOHL'S CORP ---------------------------------
---------------------------------  COMPUWARE CORP ---------------------------------
---------------------------------  FOURRNERS PROPERTY TR ---------------------------------
---------------------------------  INGEVITY CORP ---------------------------------
ALLERGAN PLC brentlsaunders
ALLERGAN PLC meury_bill
---------------------------------  ADVANSIX INC ---------------------------------
FOSSIL Fossil
FOSSIL fossilenergygov
FOSSIL JDFossilBedsNPS
FOSSIL FlorissantNPS
---------------------------------  BROOKFIELD PROPERTY REIT ---------------------------------
---------------------------------  LAMB WESTON HOLDINGS ---------------------------------
---------------------------------  INCYTE CORP ---------------------------------
SIMON PROPERTY _simonlambert
---------------------------------  MID AMERICA APT CMNTYS ---------------------------------
---------------------------------  QLOGIC CORP ---------------------------------
---------------------------------  BIOVERATIV INC ---------------------------------
---------------------------------  WESTROCK CO ---------------------------------
---------------------------------  AVALONBAYMMUNITIES ---------------------------------
---------------------------------  AK STEEL HOLDING ---------------------------------
---------------------------------  PROLOGIS INC ---------------------------------
---------------------------------  LEHMAN BROTHERS HOLDINGS ---------------------------------
---------------------------------  APARTMENT INVST & MGMT ---------------------------------
---------------------------------  AFFILIATEDMPUTER SERVICES ---------------------------------
---------------------------------  REALTYOME ---------------------------------
---------------------------------  TECHNIPFMC PLC ---------------------------------
APOLLO EDUCATION ApolloTheater
BAKER HUGHES Avitas_Systems
---------------------------------  JBG SMITH PPTYS ---------------------------------
DOW INC DowNewsroom
DOW INC DowPackaging
DOW INC DuPont_News
CAMERON INTERNATIONAL cameron_tiff
DISH NETWORK dish_answers
DISH NETWORK CBSSportsNet
DISH NETWORK carriesheffield
DISH NETWORK freespeechtv
DISH NETWORK DishMx
---------------------------------  SUNEDISON INC ---------------------------------
---------------------------------  EVEREST RE LTD ---------------------------------
---------------------------------  DIAMOND OFFSHRE DRILLING ---------------------------------
---------------------------------  QWESTMMUNICATION ---------------------------------
ALTABA INC Yahoo
ALTABA INC YahooSG
DEAN FOODS TysonFoodsCEO
ABERCROMBIE & FITCH Abercrombie
ABERCROMBIE & FITCH AbercrombieHelp
ABERCROMBIE & FITCH abercrombiekids
ENDO INTERNATIONAL TheLancetEndo
---------------------------------  IMS HEALTH HOLDINGS ---------------------------------
---------------------------------  CIENA CORP ---------------------------------
---------------------------------  ALEXANDRIA R E EQUITIES ---------------------------------
BOSTON PROPERTIES PeterSouhleris
UNITED RENTALS UnitedRentals
---------------------------------  AMCOR PLC ---------------------------------
NIELSEN HOLDINGS nielsen
---------------------------------  CNX RESOURCESORATION ---------------------------------
REYNOLDS AMERICAN coreyreynoldsLA
---------------------------------  SBAMMUNICATIONS ---------------------------------
---------------------------------  HUDSON CITY BANCORP ---------------------------------
AGILENT TECHNOLOGIES AgilentChem
TAPESTRY INC Coach
GLOBAL PAYMENTS VisaNews
GLOBAL PAYMENTS DiscoverGlobal
GLOBAL PAYMENTS Blackhawk
WILLIS TOWERS WATSON WTWesp
---------------------------------  CENTENE CORP ---------------------------------
---------------------------------  TRANSDIGM ---------------------------------
CIT Canberra_CIT
CIT CitImmCanada
CIT FedCitSci
CIT MCNocando
CIT CitAdviceScot
CIT IMA_CitRights
CIT NatCitAlliance
CIT CitSciBio
---------------------------------  QEP RESOURCES ---------------------------------
---------------------------------  ASSURANT INC ---------------------------------
---------------------------------  MARKETAXESS HOLDINGS ---------------------------------
---------------------------------  HOSPIRA INC ---------------------------------
---------------------------------  METROPCSMMUNICATIONS ---------------------------------
MOSAIC CO SuttonBStracke
---------------------------------  CF INDUSTRIES HOLDINGS ---------------------------------
---------------------------------  LEIDOS HOLDINGS ---------------------------------
NYSE EURONEXT artmarketdotcom
NYSE EURONEXT nokia
---------------------------------  DIAMONDBACK ENERGY ---------------------------------
WINDSTREAM HOLDINGS Windstream
TIME WARNER CABLE SpectrumSN
TIME WARNER CABLE SportsNetLA
TIME WARNER CABLE Mike_Bresnahan
TIME WARNER CABLE spectrumcenter
---------------------------------  BROADRIDGE FINANCIAL SOLUTNS ---------------------------------
---------------------------------  COVIDIEN PLC ---------------------------------
---------------------------------  CAREFUSION CORP ---------------------------------
---------------------------------  FLEETCOR TECHNOLOGIES ---------------------------------
---------------------------------  MOTOROLA MOBILITY HLDGS ---------------------------------
---------------------------------  HUNTINGTON INGALLS IND ---------------------------------
---------------------------------  WPX ENERGY ---------------------------------
---------------------------------  FORTUNE BRANDS HOME & SECUR ---------------------------------
---------------------------------  CAPRI HOLDINGS LTD ---------------------------------
---------------------------------  LYONDELLBASELL INDUSTRIES NV ---------------------------------

In [42]:
len(badnames)

115

In [50]:
columns = ['GVKEY', 'Company', 'Company_Handles', 'bio', 'verified']
tdf = pd.DataFrame(list(zip(gvk, companies, handles, descriptions, verified)), columns =columns) 
tdf.dropna(inplace=True)
tdf= tdf[tdf['verified']!=False]
tdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 259 entries, 0 to 258
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GVKEY            259 non-null    int64
 1   Company          259 non-null    object
 2   Company_Handles  259 non-null    object
 3   bio              259 non-null    object
 4   verified         259 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 10.4+ KB

In [64]:
dfs=tdf[tdf['Company'].map(tdf['Company'].value_counts()) == 1]
dfs

,GVKEY,Company,Company_Handles,bio,verified
0,1177,AETNA INC,Aetna,"Every day, as part of @CVSHealth, we join you ...",True
1,1440,AMERICAN ELECTRIC POWER,AEPnews,"The Official AEP account for latest news, info...",True
8,1837,SOUTHERN GAS,SSGC_Official,Sui Southern Gas Company is Pakistan's leading...,True
9,1891,AUTOMATIC DATA PROCESSING,ADP,"HR, Talent, Time Management, Benefits and Payr...",True
11,1995,CONSTELLATION ENERGY,ConstellationEG,"Constellation, an Exelon company, is a leading...",True
12,2019,BANK OF NEW YORK MELLON,BNYMellon,BNY Mellon delivers informed investment manage...,True
43,4016,DOLLAR GENERAL,DollarGeneral,"With 17,000 stores, we’re here to Serve Others...",True
44,4087,DU PONT DE NEMOURS,DuPont_News,For over 200 years DuPont has been innovating ...,True
58,4843,FOREST LABORATORIES,meury_bill,Chief Commercial Officer @allergan,True
64,6307,SEARS HOLDINGS,Sears,"making moments matter™. The big, the little, t...",True
67,6653,LEGG MASON,CitiOpen,🎾 ATP 500 & WTA International Series Tournamen...,True
68,6682,JEFFERIES FINANCIAL,HandlerRich,CEO Jefferies Financial Group/Board Chair U of...,True
75,6788,RANGE RESOURCES,SignifyUni,Brighter by the day! Signify Lighting Academy ...,True
92,7637,MYLAN NV,MylanNews,"We have combined with Upjohn, formerly a divis...",True
101,7977,XCEL ENERGY,XcelEnergyCtr,America’s most intimate arena. Home of the @mn...,True
102,8247,PPG INDUSTRIES,PPG,"A global innovator in paints, coatings and mat...",True
103,8488,APPLIED BIOSYSTEMS,thermofisher,Thermo Fisher Scientific Inc. is the world lea...,True
106,9063,AUTONATION INC,CEOMikeJackson,"Executive Chairman and CEO of AutoNation, Inc.",True
107,9459,SCHERING PLOUGH,Merck,We have always been and always will be inventi...,True
130,10787,TYCO INTERNATIONAL,johnsoncontrols,"105,000 experts globally, dedicated to protect...",True
131,10920,UNITED PARCEL SERVICE,UPS,Stay connected to global trade & logistics. Tw...,True
136,11550,WEC ENERGY,aBayraktar1,"Bakan Yardımcısı, Enerji ve Tabii Kaynaklar Ba...",True
137,11856,TRUIST FINANCIAL,TruistNews,@BBT and @SunTrust have joined to become Truis...,True
154,13003,JOY GLOBAL,VDay,Global Activist Movement to End Violence Again...,True
155,13041,SYNOVUS FINANCIAL,synovus,Synovus (NYSE:SNV) provides retail and commerc...,True
158,15708,ALLERGAN INC,meury_bill,Chief Commercial Officer @allergan,True
159,16243,WASHINGTON MUTUAL,indiviglio,Former Reuters Breakingviews Washington column...,True
183,23978,UNITED STATES STEEL,dennisogbe,Man of Steel with Heart of Gold and Survivor o...,True
202,24316,MONSTER BEVERAGE,MonsterEnergy,#UnleashTheBeast\nhttps://t.co/qgChRebwPI\nhtt...,True
203,24318,XL LTD,qikipedia,A Quite Interesting Twitter feed from the team...,True
206,24782,PERRIGO,billyperrigo,Reporter @TIME. DM me for secure contact details,True
207,24975,SYNOPSYS INC,SW_Integrity,The official Twitter account for @Synopsys Sof...,True
214,29389,SIMON PROPERTY,_simonlambert,This is Money Editor and in charge of MailOnli...,True
215,31122,APOLLO EDUCATION,ApolloTheater,The Soul of American Culture • President & CEO...,True
220,60894,CAMERON INTERNATIONAL,cameron_tiff,"Artistic Director, TIFF",True
228,62655,DEAN FOODS,TysonFoodsCEO,#RaisingExpectations\n#TysonCommunities,True
232,63645,ENDO INTERNATIONAL,TheLancetEndo,"Your leading source of international, cutting-...",True
233,64925,BOSTON PROPERTIES,PeterSouhleris,Love buying and rehabbing properties....Archit...,True
234,66065,UNITED RENTALS,UnitedRentals,The official Twitter account for United Rental...,True
235,100873,NIELSEN HOLDINGS,nielsen,Helping the world understand media insights. 📺,True
236,120877,REYNOLDS AMERICAN,coreyreynoldsLA,Actor/Writer/Producer-Resident Alien🤠-All-Amer...,True
237,126554,AGILENT TECHNOLOGIES,AgilentChem,Agilent's Chemical Analysis Group offers lab &...,True
238,140541,TAPESTRY INC,Coach,The original American house of leather.,True
242,144009,WILLIS TOWERS WATSON,WTWesp,Tú ves el futuro. Nosotros te ayudamos a llega...,True
251,162129,MOSAIC CO,SuttonBStracke,Mom of 3. Art & fashion lover. Official Cast m...,True
254,174490,WINDSTREAM HOLDINGS,Windstream,Windstream is an innovative communications & s...,True

In [65]:
dff= pd.concat([df, dfs], axis=0)
dff

,GVKEY,Company,Company_Handles,bio,verified
0,1045,AMERICAN AIRLINES GROUP INC,americanair,Official Twitter for the world’s largest airli...,True
1,1078,ABBOTT LABORATORIES,abbottglobal,The @AbbottGlobal Twitter page was discontinue...,True
2,1161,ADVANCED MICRO DEVICES,amd,Official corporate news about the AMD technolo...,True
4,1209,AIR PRODUCTS & CHEMICALS INC,AirProducts,"Industry-leading company of 19,000+ dedicated ...",True
5,1230,ALASKA AIR GROUP INC,alaskaair,We’ve now reached tweeting altitude. ✈️ Our So...,True
...,...,...,...,...,...
237,126554,AGILENT TECHNOLOGIES,AgilentChem,Agilent's Chemical Analysis Group offers lab &...,True
238,140541,TAPESTRY INC,Coach,The original American house of leather.,True
242,144009,WILLIS TOWERS WATSON,WTWesp,Tú ves el futuro. Nosotros te ayudamos a llega...,True
251,162129,MOSAIC CO,SuttonBStracke,Mom of 3. Art & fashion lover. Official Cast m...,True
254,174490,WINDSTREAM HOLDINGS,Windstream,Windstream is an innovative communications & s...,True

In [66]:
len(tdf.Company.unique())

83

In [61]:
df=df[~df.bio.isna()]

In [67]:
dff.drop_duplicates()

,GVKEY,Company,Company_Handles,bio,verified
0,1045,AMERICAN AIRLINES GROUP INC,americanair,Official Twitter for the world’s largest airli...,True
1,1078,ABBOTT LABORATORIES,abbottglobal,The @AbbottGlobal Twitter page was discontinue...,True
2,1161,ADVANCED MICRO DEVICES,amd,Official corporate news about the AMD technolo...,True
4,1209,AIR PRODUCTS & CHEMICALS INC,AirProducts,"Industry-leading company of 19,000+ dedicated ...",True
5,1230,ALASKA AIR GROUP INC,alaskaair,We’ve now reached tweeting altitude. ✈️ Our So...,True
...,...,...,...,...,...
237,126554,AGILENT TECHNOLOGIES,AgilentChem,Agilent's Chemical Analysis Group offers lab &...,True
238,140541,TAPESTRY INC,Coach,The original American house of leather.,True
242,144009,WILLIS TOWERS WATSON,WTWesp,Tú ves el futuro. Nosotros te ayudamos a llega...,True
251,162129,MOSAIC CO,SuttonBStracke,Mom of 3. Art & fashion lover. Official Cast m...,True
254,174490,WINDSTREAM HOLDINGS,Windstream,Windstream is an innovative communications & s...,True

In [68]:
dfb= pd.DataFrame(list(zip(badgv, badnames)), columns =['GVKEY', 'Company'])
dfb

      GVKEY                       Company
0      1013        ADC TELECOMMUNICATIONS
1      1075         PINNACLE WEST CAPITAL
2      1318                   ALLTEL CORP
3      1661         NABORS INDUSTRIES LTD
4      1794       ASHLAND GLOBAL HOLDINGS
..      ...                           ...
110  186310        HUNTINGTON INGALLS IND
111  187128                    WPX ENERGY
112  188255   FORTUNE BRANDS HOME & SECUR
113  198058            CAPRI HOLDINGS LTD
114  294524  LYONDELLBASELL INDUSTRIES NV

[115 rows x 2 columns]

In [69]:
dfb.to_csv('Bad Names/badnames_gsearch.csv', index=False)

In [71]:
dff.Company.unique().tolist()

['AMERICAN AIRLINES GROUP INC',
 'ABBOTT LABORATORIES',
 'ADVANCED MICRO DEVICES',
 'AIR PRODUCTS & CHEMICALS INC',
 'ALASKA AIR GROUP INC',
 'HONEYWELL INTERNATIONAL INC',
 'ALCOA INC',
 'HESS CORP',
 'BEAM INC',
 'AMERICAN EXPRESS CO',
 'AFLAC INC',
 'AMERICAN INTERNATIONAL GROUP',
 'AMGEN INC',
 'ANHEUSER-BUSCH COS INC',
 'AUTODESK INC',
 'AVERY DENNISON CORP',
 'AVON PRODUCTS',
 'VERIZON COMMUNICATIONS INC',
 'BEMIS CO INC',
 'BERKSHIRE HATHAWAY',
 'BEST BUY CO INC',
 'BLACK & DECKER CORP',
 'BLOCK H & R INC',
 'BOEING CO',
 'OFFICEMAX INC',
 'ROBERT HALF INTL INC',
 'BRISTOL-MYERS SQUIBB CO',
 'BROWN FORMAN CORP',
 'CIGNA CORP',
 'CAMPBELL SOUP CO',
 'CONSTELLATION BRANDS',
 'CARDINAL HEALTH INC',
 'CATERPILLAR INC',
 'CENTURYLINK INC',
 'JPMORGAN CHASE & CO',
 'CHEVRON CORP',
 'CHUBB CORP',
 'IHEARTMEDIA INC',
 'CLOROX CO/DE',
 'COCA-COLA CO',
 'COLGATE-PALMOLIVE CO',
 'AON PLC',
 'COMCAST CORP',
 'CITIGROUP INC',
 'DXC TECHNOLOGY CO',
 'CONAGRA BRANDS INC',
 'CONSOLIDATED EDISON INC',
 'MOLSON COORS BEVERAGE CO',
 'CORNING INC',
 'CUMMINS INC',
 'DEERE & CO',
 'DELTA AIR LINES INC',
 'DTE ENERGY CO',
 'ADTALEM GLOBAL EDUCATION INC',
 'DILLARDS INC  -CL A',
 'DOMINION ENERGY INC',
 'DOVER CORP',
 'DUPONT DE NEMOURS INC',
 'DUKE ENERGY CORP',
 'DUN & BRADSTREET CORP',
 'PERKINELMER INC',
 'EASTMAN KODAK CO',
 'ECOLAB INC',
 'EL PASO CORP',
 'EMERSON ELECTRIC CO',
 'WEATHERFORD INTL PLC',
 'ATMOS ENERGY CORP',
 'EQUIFAX INC',
 'EXXON MOBIL CORP',
 'NEXTERA ENERGY INC',
 'FAMILY DOLLAR STORES',
 'FEDEX CORP',
 "MACY'S INC",
 'FIFTH THIRD BANCORP',
 'REGIONS FINANCIAL CORP',
 'M & T BANK CORP',
 'U S BANCORP',
 'FORD MOTOR CO',
 'FRANKLIN RESOURCES INC',
 'TEGNA INC',
 'GAP INC',
 'GENERAL DYNAMICS CORP',
 'GENERAL ELECTRIC CO',
 'GENERAL MILLS INC',
 'GENERAL MOTORS CO',
 'GOODYEAR TIRE & RUBBER CO',
 'GRAINGER (W W) INC',
 'HALLIBURTON CO',
 'HASBRO INC',
 'KRAFT HEINZ CO',
 'HERCULES INC',
 'HERSHEY CO',
 'HP INC',
 'HILTON WORLDWIDE HOLDINGS',
 'HOME DEPOT INC',
 'HORMEL FOODS CORP',
 'STARWOOD HOTELS&RESORTS WRLD',
 'HUNTINGTON BANCSHARES',
 'ITT INC',
 'INTEL CORP',
 'INTERPUBLIC GROUP OF COS',
 'JOHNSON & JOHNSON',
 'JOHNSON CONTROLS INTL PLC',
 'KLA CORP',
 'KELLOGG CO',
 'KROGER CO',
 'LSI CORP',
 'LENNAR CORP',
 'LILLY (ELI) & CO',
 'LINCOLN NATIONAL CORP',
 'KATE SPADE & CO',
 'LOCKHEED MARTIN CORP',
 'LOEWS CORP',
 "LOWE'S COS INC",
 'MATTEL INC',
 "MCDONALD'S CORP",
 'S&P GLOBAL INC',
 'MCKESSON CORP',
 'MEDTRONIC PLC',
 'CVS HEALTH CORP',
 'MERCK & CO',
 'MEREDITH CORP',
 'MICRON TECHNOLOGY INC',
 'ENTERGY CORP',
 '3M CO',
 'MOTOROLA SOLUTIONS INC',
 'BANK OF AMERICA CORP',
 'NCR CORP',
 'NEW YORK TIMES CO  -CL A',
 'NORDSTROM INC',
 'EVERSOURCE ENERGY',
 'NORTHERN TRUST CORP',
 'NORTHROP GRUMMAN CORP',
 'WELLS FARGO & CO',
 'PNC FINANCIAL SVCS GROUP INC',
 'PG&E CORP',
 'PAYCHEX INC',
 'PENNEY (J C) CO',
 'PPL CORP',
 'PEPSICO INC',
 'PFIZER INC',
 'EXELON CORP',
 'CONOCOPHILLIPS',
 'PVH CORP',
 'PITNEY BOWES INC',
 'PEPCO HOLDINGS INC',
 'PROCTER & GAMBLE CO',
 'ROCKWELL AUTOMATION',
 'ROLLINS INC',
 'SAFEWAY INC',
 'ST JUDE MEDICAL INC',
 'SHERWIN-WILLIAMS CO',
 'SIGMA-ALDRICH CORP',
 'SMITH INTERNATIONAL INC',
 'SMUCKER (JM) CO',
 'KEYCORP',
 'SOUTHWEST AIRLINES',
 'AT&T INC',
 'STANLEY BLACK & DECKER INC',
 'STATE STREET CORP',
 'PUBLIC STORAGE',
 'NAVIENT CORP',
 'SUNTRUST BANKS INC',
 'ANDEAVOR',
 'TEXAS INSTRUMENTS INC',
 'TEXTRON INC',
 'THERMO FISHER SCIENTIFIC INC',
 'TOTAL SYSTEM SERVICES INC',
 'TRIBUNE MEDIA CO',
 'TYSON FOODS INC  -CL A',
 'UNITED AIRLINES HOLDINGS INC',
 'AMEREN CORP',
 'UNION PACIFIC CORP',
 'UNITEDHEALTH GROUP INC',
 'RAYTHEON TECHNOLOGIES CORP',
 'SPRINT CORP',
 'VF CORP',
 'VULCAN MATERIALS CO',
 'WALMART INC',
 'WESTERN DIGITAL CORP',
 'WHIRLPOOL CORP',
 'WILLIAMS COS INC',
 'FOOT LOCKER INC',
 'XEROX HOLDINGS CORP',
 'BIG LOTS INC',
 'MORGAN STANLEY',
 'PRICE (T. ROWE) GROUP',
 'MICROSOFT CORP',
 'ORACLE CORP',
 'COTY INC',
 'DIRECTV',
 'HARLEY-DAVIDSON INC',
 'GARTNER INC',
 'ADOBE INC',
 'FISERV INC',
 'KB HOME',
 'COCA-COLA EUROPEAN PARTNERS',
 'HARMAN INTERNATIONAL INDS',
 'CERNER CORP',
 'KRAFT FOODS GROUP INC',
 'LEVEL 3 COMMUNICATIONS INC',
 'TIFFANY & CO',
 'VIACOMCBS INC',
 'SCHWAB (CHARLES) CORP',
 'FASTENAL CO',
 'FIRST REPUBLIC BANK',
 'MGM RESORTS INTERNATIONAL',
 'ADT CORP',
 'WASTE MANAGEMENT INC',
 'DELL TECHNOLOGIES INC',
 'EW SCRIPPS  -CL A',
 'OFFICE DEPOT INC',
 'BMC SOFTWARE INC',
 'DEVON ENERGY CORP',
 'FEDERAL HOME LOAN MORTG CORP',
 'VALERO ENERGY CORP',
 'STAPLES INC',
 'NORTONLIFELOCK INC',
 'ABBVIE INC',
 'ELECTRONIC ARTS INC',
 'PTC INC',
 'CAESARS ENTERTAINMENT CORP',
 'CABOT OIL & GAS CORP',
 'SYNCHRONY FINANCIAL',
 'ARISTA NETWORKS INC',
 'CITIZENS FINANCIAL GROUP INC',
 'HCA HEALTHCARE INC',
 'XILINX INC',
 'AUTOZONE INC',
 'REGENERON PHARMACEUTICALS',
 'VERTEX PHARMACEUTICALS INC',
 'BIOGEN INC',
 'QUALCOMM INC',
 'GILEAD SCIENCES INC',
 'WHOLE FOODS MARKET INC',
 'LINDE PLC',
 'FIRST DATA CORP',
 'BOSTON SCIENTIFIC CORP',
 'BED BATH & BEYOND INC',
 'D R HORTON INC',
 'EXPRESS SCRIPTS HOLDING CO',
 'STARBUCKS CORP',
 'MCAFEE INC',
 'HEWLETT PACKARD ENTERPRISE',
 'ADIENT PLC',
 'CHESAPEAKE ENERGY CORP',
 'HUMANA INC',
 'INTUIT INC',
 'MICROCHIP TECHNOLOGY INC',
 'CHUBB LTD',
 "O'REILLY AUTOMOTIVE INC",
 'ROYAL CARIBBEAN CRUISES LTD',
 'JABIL INC',
 'ALLSTATE CORP',
 'PETSMART INC',
 'KEURIG DR PEPPER INC',
 'MARRIOTT INTL INC',
 'URBAN OUTFITTERS INC',
 'EASTMAN CHEMICAL CO',
 'INVESCO LTD',
 'CAPITAL ONE FINANCIAL CORP',
 'BRIGHTHOUSE FINANL INC',
 'DARDEN RESTAURANTS INC',
 'CHAMPIONX CORP',
 'PERSPECTA INC',
 'FOX CORP',
 'KONTOOR BRANDS INC',
 'CORTEVA INC',
 'DAVITA INC',
 'HENRY SCHEIN INC',
 'SANDISK CORP',
 'WATERS CORP',
 'NETAPP INC',
 'CITRIX SYSTEMS INC',
 'HARTFORD FINANCIAL SERVICES',
 'ALEXION PHARMACEUTICALS INC',
 'TRAVELERS COS INC',
 'ANSYS INC',
 'E TRADE FINANCIAL CORP',
 'UNIVISION COMMUNICATIONS INC',
 'NATIONAL OILWELL VARCO INC',
 'MONSTER WORLDWIDE INC',
 'QUEST DIAGNOSTICS INC',
 'CARMAX INC',
 'TAKE-TWO INTERACTIVE SFTWR',
 'AMAZON.COM INC',
 'RALPH LAUREN CORP',
 'YUM BRANDS INC',
 'VERISIGN INC',
 'BROADCOM CORP',
 'NORWEGIAN CRUISE LINE HLDGS',
 'COGNIZANT TECH SOLUTIONS',
 'REPUBLIC SERVICES INC',
 'EBAY INC',
 'GOLDMAN SACHS GROUP INC',
 'NVIDIA CORP',
 'APTIV PLC',
 'LIFE TECHNOLOGIES CORP',
 'BOOKING HOLDINGS INC',
 'PEPSI BOTTLING GROUP INC',
 'JUNIPER NETWORKS INC',
 'RED HAT INC',
 'BLACKROCK INC',
 'AKAMAI TECHNOLOGIES INC',
 'CHARTER COMMUNICATIONS INC',
 'EXPEDIA GROUP INC',
 'EDWARDS LIFESCIENCES CORP',
 'METLIFE INC',
 'FRONTIER COMMUNICATIONS CORP',
 'NRG ENERGY INC',
 'GARMIN LTD',
 'PEABODY ENERGY CORP',
 'MONDELEZ INTERNATIONAL INC',
 'PRUDENTIAL FINANCIAL INC',
 'ACCENTURE PLC',
 'ANTHEM INC',
 'GAMESTOP CORP',
 'PRINCIPAL FINANCIAL GRP INC',
 'ADVANCE AUTO PARTS INC',
 'NETFLIX INC',
 'CME GROUP INC',
 'WYNN RESORTS LTD',
 'NASDAQ INC',
 'SEAGATE TECHNOLOGY PLC',
 'SALESFORCE.COM INC',
 'GENWORTH FINANCIAL INC',
 'MASTERCARD INC',
 'EXTRA SPACE STORAGE INC',
 'DIGITAL REALTY TRUST INC',
 'INTERCONTINENTAL EXCHANGE',
 'DISCOVERY INC',
 'AMERIPRISE FINANCIAL INC',
 'UNDER ARMOUR INC',
 'CHIPOTLE MEXICAN GRILL INC',
 'FIDELITY NATIONAL INFO SVCS',
 'FACEBOOK INC',
 'PHILLIPS 66',
 'REALOGY HOLDINGS CORP',
 'WYNDHAM DESTINATIONS INC',
 'WESTERN UNION CO',
 'TE CONNECTIVITY LTD',
 'DISCOVER FINANCIAL SVCS',
 'MSCI INC',
 'ULTA BEAUTY INC',
 'AMERICAN WATER WORKS CO INC',
 'VISA INC',
 'DR PEPPER SNAPPLE GROUP INC',
 'ACTIVISION BLIZZARD INC',
 'BROADCOM INC',
 'FORTINET INC',
 'CBOE GLOBAL MARKETS INC',
 'MARATHON PETROLEUM CORP',
 'TRIPADVISOR INC',
 'CBRE GROUP INC',
 'BURLINGTON NORTHERN SANTA FE',
 'OMNICOM GROUP',
 'ELECTRONIC DATA SYSTEMS CORP',
 'HUNT (JB) TRANSPRT SVCS INC',
 'KIMBERLY-CLARK CORP',
 'NIKE INC  -CL B',
 'PUBLIC SERVICE ENTRP GRP INC',
 'PULTEGROUP INC',
 'SOUTHERN CO',
 'SUPERVALU INC',
 'WALGREENS BOOTS ALLIANCE INC',
 'CISCO SYSTEMS INC',
 'TIME WARNER INC',
 'CSRA INC',
 'CARS.COM INC',
 'LAUDER (ESTEE) COS INC -CL A',
 'AMERICAN CAPITAL LTD',
 'ILLUMINA INC',
 'ALPHA NATURAL RESOURCES INC',
 'EMBARQ CORP',
 'PHILIP MORRIS INTERNATIONAL',
 'AETNA INC',
 'AMERICAN ELECTRIC POWER',
 'SOUTHERN GAS',
 'AUTOMATIC DATA PROCESSING',
 'CONSTELLATION ENERGY',
 'BANK OF NEW YORK MELLON',
 'DOLLAR GENERAL',
 'DU PONT  DE NEMOURS',
 'FOREST LABORATORIES',
 'SEARS HOLDINGS',
 'LEGG MASON',
 'JEFFERIES FINANCIAL',
 'RANGE RESOURCES',
 'MYLAN NV',
 'XCEL ENERGY',
 'PPG INDUSTRIES',
 'APPLIED BIOSYSTEMS',
 'AUTONATION INC',
 'SCHERING PLOUGH',
 'TYCO INTERNATIONAL',
 'UNITED PARCEL SERVICE',
 'WEC ENERGY',
 'TRUIST FINANCIAL',
 'JOY GLOBAL',
 'SYNOVUS FINANCIAL',
 'ALLERGAN INC',
 'WASHINGTON MUTUAL',
 'UNITED STATES STEEL',
 'MONSTER BEVERAGE',
 'XL LTD',
 'PERRIGO',
 'SYNOPSYS INC',
 'SIMON PROPERTY',
 'APOLLO EDUCATION',
 'CAMERON INTERNATIONAL',
 'DEAN FOODS',
 'ENDO INTERNATIONAL',
 'BOSTON PROPERTIES',
 'UNITED RENTALS',
 'NIELSEN HOLDINGS',
 'REYNOLDS AMERICAN',
 'AGILENT TECHNOLOGIES',
 'TAPESTRY INC',
 'WILLIS TOWERS WATSON',
 'MOSAIC CO',
 'WINDSTREAM HOLDINGS']

In [72]:
badnames

['ADC TELECOMMUNICATIONS',
 'PINNACLE WEST CAPITAL',
 'ALLTEL CORP',
 'NABORS INDUSTRIES LTD',
 'ASHLAND GLOBAL HOLDINGS',
 'UNISYS CORP',
 'CSX CORP',
 'CIRCUIT CITY STORES',
 'EXPEDITORS WASH',
 'FEDERAL NATIONAL MORTGA ASSN',
 'FEDERAL REALTY INVESTMENT TR',
 'FIRST HORIZON NATIONAL',
 'WELLTOWER INC',
 'HOLLYFRONTIER CORP',
 'INTL BUSINESS MACHINES',
 'INTL FLAVORS & FRAGRANCES',
 'MARSH & MCLENNANS',
 'MARSHALL & ILSLEY',
 'MASCO CORP',
 'MEDCO HEALTH SOLUTIONS',
 'MOLEX INC',
 'NICOR INC',
 'ONEOK INC',
 'PACCAR INC',
 'PARKER HANNIFIN CORP',
 'PENTAIR PLC',
 'ROHM AND HAAS',
 'ROWANMPANIES',
 'SAFECO CORP',
 'SCANA CORP',
 'TEMPLE INLAND INC',
 'TERADYNE INC',
 'ENERGY FUTURE HOLDINGS',
 'VORNADO REALTY TRUST',
 'MEADWESTVACO CORP',
 'WEYERHAEUSER CO',
 'INTEGRYS HOLDING',
 'ZIONS BANCORPORATION NA',
 'BEAR STEARNSMPANIES',
 'EMC CORP/MA',
 'GENZYME CORP',
 'AIRGAS INC',
 'HEALTHPEAK PROPERTIES',
 'PROGRESSIVE CORP OHIO',
 'BARR PHARMACEUTICALS',
 'CARNIVALORATION &',
 'ZOETIS INC',
 'MAXIM INTEGRATED PRODUCTS',
 'ALTERA CORP',
 'LABORATORY CP OF AMER HLDGS',
 "PEOPLE'S UNITED FINL",
 'COMMERCE BANCORP/NJ',
 'SANTANDER HOLDINGS USA',
 'IQVIA HOLDINGS',
 'MALLINCKRODT PLC',
 'DENBURY RESOURCES',
 'ALLIED WASTE INDUSTRIES',
 'BAXALTA INC',
 'PMC SIERRA INC',
 'CEPHALON INC',
 'AMBAC FINANCIAL',
 'MGIC INVESTMENT/WI',
 'ROPER TECHNOLOGIES',
 "KOHL'S CORP",
 'COMPUWARE CORP',
 'FOURRNERS PROPERTY TR',
 'INGEVITY CORP',
 'ADVANSIX INC',
 'BROOKFIELD PROPERTY REIT',
 'LAMB WESTON HOLDINGS',
 'INCYTE CORP',
 'MID AMERICA APT CMNTYS',
 'QLOGIC CORP',
 'BIOVERATIV INC',
 'WESTROCK CO',
 'AVALONBAYMMUNITIES',
 'AK STEEL HOLDING',
 'PROLOGIS INC',
 'LEHMAN BROTHERS HOLDINGS',
 'APARTMENT INVST & MGMT',
 'AFFILIATEDMPUTER SERVICES',
 'REALTYOME',
 'TECHNIPFMC PLC',
 'JBG SMITH PPTYS',
 'SUNEDISON INC',
 'EVEREST RE LTD',
 'DIAMOND OFFSHRE DRILLING',
 'QWESTMMUNICATION',
 'IMS HEALTH HOLDINGS',
 'CIENA CORP',
 'ALEXANDRIA R E EQUITIES',
 'AMCOR PLC',
 'CNX RESOURCESORATION',
 'SBAMMUNICATIONS',
 'HUDSON CITY BANCORP',
 'CENTENE CORP',
 'TRANSDIGM',
 'QEP RESOURCES',
 'ASSURANT INC',
 'MARKETAXESS HOLDINGS',
 'HOSPIRA INC',
 'METROPCSMMUNICATIONS',
 'CF INDUSTRIES HOLDINGS',
 'LEIDOS HOLDINGS',
 'DIAMONDBACK ENERGY',
 'BROADRIDGE FINANCIAL SOLUTNS',
 'COVIDIEN PLC',
 'CAREFUSION CORP',
 'FLEETCOR TECHNOLOGIES',
 'MOTOROLA MOBILITY HLDGS',
 'HUNTINGTON INGALLS IND',
 'WPX ENERGY',
 'FORTUNE BRANDS HOME & SECUR',
 'CAPRI HOLDINGS LTD',
 'LYONDELLBASELL INDUSTRIES NV']

In [74]:
dfb.GVKEY.unique().tolist()

[1013,
 1075,
 1318,
 1661,
 1794,
 2504,
 2574,
 3054,
 4494,
 4601,
 4605,
 4737,
 5543,
 5667,
 6066,
 6078,
 7065,
 7067,
 7085,
 7186,
 7506,
 7904,
 8151,
 8253,
 8358,
 8463,
 9217,
 9258,
 9351,
 9445,
 10426,
 10453,
 10507,
 11220,
 11446,
 11456,
 11555,
 11687,
 11818,
 12053,
 12233,
 12950,
 13125,
 13341,
 13365,
 13498,
 13721,
 14256,
 14324,
 14960,
 16245,
 16784,
 17130,
 17928,
 18086,
 20653,
 22140,
 22734,
 23943,
 23945,
 24287,
 24379,
 24925,
 25283,
 26011,
 26410,
 27119,
 28070,
 28119,
 28790,
 29127,
 29649,
 29791,
 29819,
 29830,
 29875,
 29968,
 29984,
 30128,
 30490,
 30697,
 30822,
 30923,
 32154,
 60992,
 61388,
 61409,
 61489,
 63800,
 64356,
 64821,
 100243,
 120093,
 121382,
 122015,
 145552,
 148349,
 154357,
 157057,
 158742,
 160255,
 160256,
 163946,
 165123,
 170750,
 176928,
 177264,
 183257,
 184700,
 186106,
 186310,
 187128,
 188255,
 198058,
 294524]