## INIT

In [1]:
import tweepy
import pandas as pd
import numpy as np

In [2]:
# assign the values accordingly 
consumer_key = "OMJv2A5J1XvXdBSLykjbzQvjN" 
consumer_secret = "IF1tUCs5uFhKNN4PILugYgTdfaFDEakS4gbzWHKEL92dIoSRHA" 
access_token = "3097042092-HXzJwRZ4BRSiTa67RfHnlE7CeF01gutElIP6UoT" 
access_token_secret = "kZYcycMakp0z3jcGC07UpLynOWvvtoBiAmwVjJKziSYB8"

In [3]:
# authorization of consumer key and consumer secret 
auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
# set access to user's access key and access secret  
auth.set_access_token(access_token, access_token_secret) 
  
# calling the api  
api = tweepy.API(auth, wait_on_rate_limit=True)

## Company

In [4]:
import pandas as pd
dff= pd.read_csv('Final_SnP500_companies_handles_2010to2020.csv')
dff

        GVKEY                      Company        Handle  validated
0      1661.0        NABORS INDUSTRIES LTD  NaborsGlobal          1
1      1794.0  ASHLAND GLOBAL HOLDINGS INC    AshlandInc          1
2      2504.0                  UNISYS CORP    unisyscorp          1
3      2574.0                     CSX CORP           CSX          1
4      3054.0      CIRCUIT CITY STORES INC   CircuitCity          1
..        ...                          ...           ...        ...
521   60900.0            DISH NETWORK CORP          dish          1
522   63643.0   ABERCROMBIE & FITCH  -CL A   Abercrombie          1
523   64156.0        MONSTER WORLDWIDE INC     MonsterWW          1
524  122841.0                  RED HAT INC        RedHat          1
525  141913.0          GLOBAL PAYMENTS INC  GlobalPayInc          1

[526 rows x 4 columns]

In [7]:
dff.iloc[0]

GVKEY                         1661
Company      NABORS INDUSTRIES LTD
Handle                NaborsGlobal
validated                        1
Name: 0, dtype: object

In [9]:
gvkeys=[]
companies=[]
names=[]
ids=[]
handles=[]
verified=[]
validated=[]
created_ats=[]
statuses_counts=[]
followers_counts=[]
descriptions=[]


for i in range(len(dff)):
    j= dff.iloc[i]['Handle']
    try:
        obj=api.get_user(j)
        gvkeys.append(dff.iloc[i]['GVKEY'])
        companies.append(dff.iloc[i]['Company'])
        names.append(obj.name)
        ids.append(obj.id)
        handles.append(j)
        verified.append(obj.verified)
        validated.append(dff.iloc[i]['validated'])
        created_ats.append(obj.created_at)
        statuses_counts.append(obj.statuses_count)
        followers_counts.append(obj.followers_count)
        descriptions.append(obj.description)
    except:
        print('bad user name,', j)
        pass

columns = ['GVKEY','Company', 'TwitterID', 'TwitterName', 'TwitterHandle', 'Verified(Y/N)', 'Validated', 'Since', 'TweetsCount', 'FollowersCount', 'TwitterDescr']
df = pd.DataFrame(list(zip(gvkeys,companies,ids,names,handles,verified,validated,created_ats,statuses_counts,followers_counts,descriptions)), columns =columns) 
df.to_csv("Final_SnP500_companies_handles_2010To2020.csv", index=False)

bad user name, FirstData

In [10]:
df

,GVKEY,Company,TwitterID,TwitterName,TwitterHandle,Verified(Y/N),Validated,Since,TweetsCount,FollowersCount,TwitterDescr
0,1661.0,NABORS INDUSTRIES LTD,1694623495,Nabors Industries,NaborsGlobal,False,1,2013-08-23 19:12:12,203,623,From automated rig components to integrated dr...
1,1794.0,ASHLAND GLOBAL HOLDINGS INC,294252642,Ashland,AshlandInc,False,1,2011-05-06 20:12:04,2344,2694,always solvingâ„¢
2,2504.0,UNISYS CORP,48402711,Unisys Corporation,unisyscorp,False,1,2009-06-18 16:27:50,61446,37306,Updates and insights on business developments ...
3,2574.0,CSX CORP,15724503,CSX,CSX,False,1,2008-08-04 16:51:02,5477,45811,The official Twitter feed for CSX.
4,3054.0,CIRCUIT CITY STORES INC,4869302867,Circuit City,CircuitCity,False,1,2016-02-01 14:14:33,168,699,"OH YES, WEâ€™RE BACK! Your GO TO for exclusive &..."
...,...,...,...,...,...,...,...,...,...,...,...
520,60900.0,DISH NETWORK CORP,17170147,DISH,dish,True,1,2008-11-04 21:49:26,59877,109871,We go above and beyond to deliver the best TV ...
521,63643.0,ABERCROMBIE & FITCH -CL A,270533441,Abercrombie & Fitch,Abercrombie,True,1,2011-03-22 20:01:47,3333,516839,
522,64156.0,MONSTER WORLDWIDE INC,17426969,Monster Worldwide,MonsterWW,True,1,2008-11-16 20:02:05,10573,29788,The place for all your @monster worldwide news...
523,122841.0,RED HAT INC,14627400,"Red Hat, Inc.",RedHat,True,1,2008-05-02 16:03:09,31713,212650,The leading provider of enterprise open source...
524,141913.0,GLOBAL PAYMENTS INC,478912243,Global Payments Inc.,GlobalPayInc,False,1,2012-01-30 20:11:25,2401,4255,Global Payments Inc. (NYSE: GPN) is a leading ...

In [12]:
df['Verified(Y/N)'].value_counts()

True     474
False     51
Name: Verified(Y/N), dtype: int64

# CEO

In [4]:
import pandas as pd
df= pd.read_csv(r'D:\OneDrive - Indian School of Business\Projects\Mindset\tweets\TWITTERHANDLESSEARCH\data\final\CEOs_Validated_Handles.csv')
df

,CEO,Company,YEAR,Handle,Twitter_Descr,verified,Validated
0,"Lisa T. Su, Ph.D.",ADVANCED MICRO DEVICES,2015,LisaSu,President and CEO of @AMD,True,True
1,Mark Thomas Bertolini,AETNA INC,2011,mtbert,"Devoted father, rabid hockey fan, retiree and ...",True,True
2,Timothy D. Cook,APPLE INC,2012,tim_cook,Apple CEO ? Auburn ?? ?? Duke ?? National Park...,True,True
3,Hans E. Vestberg,VERIZON COMMUNICATIONS INC,2019,hansvestberg,"Chairman and CEO of @Verizon. Avid sports fan,...",True,True
4,Warren E. Buffett,BERKSHIRE HATHAWAY,2007,WarrenBuffett,Chairman and CEO of Berkshire Hathaway,True,True
...,...,...,...,...,...,...,...
67,Jack Dorsey,TWITTER INC,2015,jack,#bitcoin,True,True
68,Margaret Cushing Whitman,HEWLETT PACKARD ENTERPRISE,2012,MegWhitman,CEO of @Quibi,True,True
69,Margaret Cushing Whitman,EBAY INC,2007,MegWhitman,CEO of @Quibi,True,True
70,Rami Rahim,JUNIPER NETWORKS INC,2015,ramirahim,CEO @JuniperNetworks. Proud to lead the next w...,True,True
71,Mauricio Gutierrez,NRG ENERGY INC,2016,NRGMauricio,President and Chief Executive Officer @NRGEnergy,True,True

In [ ]:
#gvkeys=[]
ceos=[]
names=[]
ids=[]
handles=[]
verified=[]
validated=[]
created_ats=[]
statuses_counts=[]
followers_counts=[]
descriptions=[]


for i in range(len(dff)):
    j= dff.iloc[i]['Handle']
    try:
        obj=api.get_user(j)
        gvkeys.append(dff.iloc[i]['GVKEY'])
        companies.append(dff.iloc[i]['Company'])
        names.append(obj.name)
        ids.append(obj.id)
        handles.append(j)
        verified.append(obj.verified)
        validated.append(dff.iloc[i]['validated'])
        created_ats.append(obj.created_at)
        statuses_counts.append(obj.statuses_count)
        followers_counts.append(obj.followers_count)
        descriptions.append(obj.description)
    except:
        print('bad user name,', j)
        pass

columns = ['GVKEY','Company', 'TwitterID', 'TwitterName', 'TwitterHandle', 'Verified(Y/N)', 'Validated', 'Since', 'TweetsCount', 'FollowersCount', 'TwitterDescr']
df = pd.DataFrame(list(zip(gvkeys,companies,ids,names,handles,verified,validated,created_ats,statuses_counts,followers_counts,descriptions)), columns =columns) 
df.to_csv("Final_SnP500_companies_handles_2010To2020.csv", index=False)