In [1]:
import os
import pandas as pd

In [2]:
os.chdir(r'D:\OneDrive - Indian School of Business\Projects\Mindset\tweets\TWITTERHANDLESSEARCH\kashish files\output\Verified')
os.listdir()

['Kashish_GoogleSearcher_CompanyHandles_verified.csv']

In [3]:
df= pd.read_csv('Kashish_GoogleSearcher_CompanyHandles_verified.csv')
df.shape

(375, 14)

In [5]:
df.columns

Index(['GVKEY', 'Company', 'trimmed_company_name', 'Company_Handles', 'name',
       'bio', 'join_date', 'tweets', 'following', 'followers', 'likes',
       'media', 'private', 'verified'],
      dtype='object')

In [6]:
df=df[['GVKEY', 'Company', 'Company_Handles', 'bio', 'verified']]

In [7]:
df.columns=['GVKEY', 'Company', 'Handle', 'Twitter_Descr', 'verified']
df

,GVKEY,Company,Handle,Twitter_Descr,verified
0,1045,AMERICAN AIRLINES GROUP INC,americanair,Official Twitter for the world’s largest airli...,True
1,1078,ABBOTT LABORATORIES,abbottglobal,The @AbbottGlobal Twitter page was discontinue...,True
2,1161,ADVANCED MICRO DEVICES,amd,Official corporate news about the AMD technolo...,True
3,1209,AIR PRODUCTS & CHEMICALS INC,AirProducts,"Industry-leading company of 19,000+ dedicated ...",True
4,1230,ALASKA AIR GROUP INC,alaskaair,We’ve now reached tweeting altitude. ✈️ Our So...,True
...,...,...,...,...,...
370,65345,AMERICAN CAPITAL LTD,abcapital,Protecting | Investing | Financing,True
371,138205,ILLUMINA INC,illumina,Illumina is dedicated to advancing human healt...,True
372,162448,ALPHA NATURAL RESOURCES INC,ONresources,Official account of Ontario’s Ministry of Natu...,True
373,174130,EMBARQ CORP,centurylink,Transforming lives and businesses through inno...,True
374,179621,PHILIP MORRIS INTERNATIONAL,InsidePMI,We’re designing a #smokefree future. Find out ...,True

In [8]:
df.to_csv(r'D:\OneDrive - Indian School of Business\Projects\Mindset\tweets\TWITTERHANDLESSEARCH\output\verified\Company\gsearch_verified_single handles.csv', index=False)

In [31]:
df1= pd.read_csv(r"D:\OneDrive - Indian School of Business\Projects\Mindset\tweets\TWITTERHANDLESSEARCH\output\verified\Company\tweepy_verified_single_company_handles.csv",encoding='cp437', sep=',')
#dff= pd.concat([df, df1], axis=0)
#dff
df1

,GVKEY,Company,Handle,Twitter_Descr,verified,validated
0,1078,ABBOTT LABORATORIES,AbbottNews,"This is technology at its most personal, to he...",True,1
1,1177,AETNA INC,Aetna,"Every day, as part of @CVSHealth, we join you ...",True,1
2,1209,AIR PRODUCTS & CHEMICALS INC,airproducts,"Industry-leading company of 19,000+ dedicated ...",True,1
3,1300,HONEYWELL INTERNATIONAL INC,honeywell,"At #Honeywell, we're transforming the way the ...",True,1
4,1356,ALCOA INC,Alcoa,"Alcoa is a global industry leader in bauxite, ...",True,1
...,...,...,...,...,...,...
173,179700,DR PEPPER SNAPPLE GROUP INC,DrPepperSnapple,Serving up flavorful tweets from Dr Pepper Sna...,True,1
174,183377,FORTINET INC,Fortinet,The Fortinet #SecurityFabric platform secures ...,True,1
175,184500,CBOE GLOBAL MARKETS INC,CBOE,WeÆre #DefiningMarkets to benefit all particip...,True,1
176,186989,MARATHON PETROLEUM CORP,MarathonPetroCo,Marathon Petroleum Corporation (MPC) 2020 'ENE...,True,1
177,199356,TRIPADVISOR INC,TripAdvisor,Find the good out there. #TheresGoodOutThere,True,1

In [32]:
df1.validated.value_counts()

1    155
0     23
Name: validated, dtype: int64

In [34]:
dff= df[~df.GVKEY.isin(df1.GVKEY.unique().tolist())]

In [35]:
dff

,GVKEY,Company,Handle,Twitter_Descr,verified
0,1045,AMERICAN AIRLINES GROUP INC,americanair,Official Twitter for the world’s largest airli...,True
2,1161,ADVANCED MICRO DEVICES,amd,Official corporate news about the AMD technolo...,True
4,1230,ALASKA AIR GROUP INC,alaskaair,We’ve now reached tweeting altitude. ✈️ Our So...,True
7,1380,HESS CORP,realsandrahess,"Actor, wife, mom to 4 amazing furries and wann...",True
8,1408,BEAM INC,beamng,Bringing soft-body physics to the forefront,True
...,...,...,...,...,...
370,65345,AMERICAN CAPITAL LTD,abcapital,Protecting | Investing | Financing,True
371,138205,ILLUMINA INC,illumina,Illumina is dedicated to advancing human healt...,True
372,162448,ALPHA NATURAL RESOURCES INC,ONresources,Official account of Ontario’s Ministry of Natu...,True
373,174130,EMBARQ CORP,centurylink,Transforming lives and businesses through inno...,True
374,179621,PHILIP MORRIS INTERNATIONAL,InsidePMI,We’re designing a #smokefree future. Find out ...,True

In [37]:
df1

,GVKEY,Company,Handle,Twitter_Descr,verified,validated
0,1078,ABBOTT LABORATORIES,AbbottNews,"This is technology at its most personal, to he...",True,1
1,1177,AETNA INC,Aetna,"Every day, as part of @CVSHealth, we join you ...",True,1
2,1209,AIR PRODUCTS & CHEMICALS INC,airproducts,"Industry-leading company of 19,000+ dedicated ...",True,1
3,1300,HONEYWELL INTERNATIONAL INC,honeywell,"At #Honeywell, we're transforming the way the ...",True,1
4,1356,ALCOA INC,Alcoa,"Alcoa is a global industry leader in bauxite, ...",True,1
...,...,...,...,...,...,...
173,179700,DR PEPPER SNAPPLE GROUP INC,DrPepperSnapple,Serving up flavorful tweets from Dr Pepper Sna...,True,1
174,183377,FORTINET INC,Fortinet,The Fortinet #SecurityFabric platform secures ...,True,1
175,184500,CBOE GLOBAL MARKETS INC,CBOE,WeÆre #DefiningMarkets to benefit all particip...,True,1
176,186989,MARATHON PETROLEUM CORP,MarathonPetroCo,Marathon Petroleum Corporation (MPC) 2020 'ENE...,True,1
177,199356,TRIPADVISOR INC,TripAdvisor,Find the good out there. #TheresGoodOutThere,True,1

In [38]:
list_dfs=[df1, dff[:49],dff[49:98],dff[98:147],dff[147:196],dff[196:]]
xls_path= r"D:\OneDrive - Indian School of Business\Data\singlehandles.xlsx"

def save_xls(list_dfs, xls_path):
    with pd.ExcelWriter(xls_path) as writer:
        for n, df in enumerate(list_dfs):
            df.to_excel(writer,'sheet%s' % n)
        writer.save()

save_xls(list_dfs, xls_path)

C:\ProgramData\Anaconda3\lib\site-packages\xlsxwriter\workbook.py:329: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")